development:
  adapter: postgresql
  host: localhost
  username: claudiu
  database: wantatrip_dev

production:
  adapter: ENV['HEROKU_ADAPTER']
  host: ENV['HEROKU_HOST']
  username: ENV['HEROKU_USERNAME']
  port: ENV['HEROKU_PORT']
  password: ENV['HEROKU_PASSWORD']
  database: ENV['HEROKU_DATABASE']

